### ISSUE TITLE
大佬考虑来个vue3版本的嘛？

### ISSUE THREAD

**Issue by lubulikai** [sangtian152/zm-tree-org#6]

**Comment by sangtian152** [comment]
我也想着呢，最近抽不出时间

**Comment by sangtian152** [comment]
vue3版本上线了 ，文档地址https://sangtian152.github.io/vue3-tree-org

**Comment by lubulikai** [comment]
> vue3版本上线了 ，文档地址https://sangtian152.github.io/vue3-tree-org

强啊👍
