### ISSUE TITLE
页面汉字显示undefined

### ISSUE THREAD

**Issue by xu78585** [sangtian152/zm-tree-org#7]
我们项目是公司内网，我通过引入npm install  zm-tree-org 并拷贝至内网，但是总是报http://at.alicdn.com/t/font_2201426_wnqkpnyga1.css，引入错误。如果我不引入这个，显示的汉字为undefined，请求帮助，
请问作者怎样改成一个不引入外部字体，而使用默认，cloudups@163.com谢 谢

**Comment by sangtian152** [comment]
//at.alicdn.com/t/font_2201426_wnqkpnyga1.css 是个字体图标，影响的只是右侧放大/缩小/全屏等操作按钮，如果引入错误，按钮上的图标会显示不正常，你说的汉字显示undefined，应该不是这个原因导致的
